CREATE TABLE multas (
  id INT PRIMARY KEY AUTO_INCREMENT,
  placa VARCHAR(7) NOT NULL,
  motivo VARCHAR(255) NOT NULL,
  fecha_hora_infraccion TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  correo VARCHAR(255) NOT NULL

);
